# Generated by Django 3.2.9 on 2021-12-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcomment', '0003_auto_20211201_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
