# Generated by Django 3.2.9 on 2021-12-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogcomment', '0005_postcomment_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='post',
        ),
    ]
