# Generated by Django 3.2.9 on 2021-11-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.BooleanField(default=False),
        ),
    ]
