# Generated by Django 3.2.9 on 2021-12-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isAuthor',
            new_name='is_author',
        ),
    ]
